language: java
dist: trusty

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "lumenol-github"

script:
  - mvn install
  - mvn org.pitest:pitest-maven:mutationCoverage
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar