coverage:
  range: 50..85
  round: down
  precision: 2

ignore:
  - "src/main/java/com/excilys/cdb/persistence/entity/**"
  - "src/main/java/com/excilys/cdb/persistence/exception/**"
  - "src/main/java/com/excilys/cdb/persistence/config/**"
  - "src/main/java/com/excilys/cdb/persistence/config/**"